[package]
name = "nereond"
version = "0.1.0"
authors = ["John Hedges <john@drystone.co.uk>"]

[dependencies]
base64 = "~0.6.0"
libc = "0.2"
nereon = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
