[package]
name = "nereond"
version = "0.1.1"
authors = ["John Hedges <john@drystone.co.uk>", "Ribose Inc. <open.source@ribose.com>"]

[dependencies]
base64 = "0.6"
libc = "0.2"
log = "0.4"
nereon = "0.4"
nereon_derive = "0.4"
stderrlog = "0.4"
